Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [ ]:
import numpy as np

D = np.diag([1, 2, 3])

inv_mat = np.linalg.inv(D)
print(inv_mat)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


In [ ]:
D = np.diag([1, 2, 3])

inv_mat = np.linalg.inv(D)

result = np.dot(D,inv_mat)
print(result)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [ ]:
A = np.triu(np.ones((3,3)))
print(A,'\n')

B = np.tril(np.ones((3,3)))
print(B)

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [ ]:
U = np.array([[1,2,3],[0,4,5],[0,0,6]])

U_T = U.T
print(U,'\n')
print(U_T)

[[1 2 3]
 [0 4 5]
 [0 0 6]] 

[[1 0 0]
 [2 4 0]
 [3 5 6]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [ ]:
A = np.array([[4, 7], [2, 6]])

inv_A = np.linalg.inv(A)
print(inv_A,'\n')
result = np.dot(A,inv_A)

# 단위행렬
I = np.eye(2)
print(np.allclose(result,I))

[[ 0.6 -0.7]
 [-0.2  0.4]] 

True


Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요. (행렬 곱)

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [ ]:
X = np.array([1, 2, 3])
θ= np.array([4, 5, 6])

y = np.dot(X,θ)
print(y)

32


In [ ]:
import numpy as np

# 입력 데이터 포인트
X = np.array([1, 2, 3])

# 모델 파라미터
theta = np.array([0.5, 1.5, -2])

# 선형 회귀 모델의 예측값 계산
y_pred = np.dot(X, theta)

print(X)
print(theta)
print(y_pred)

[1 2 3]
[ 0.5  1.5 -2. ]
-2.5


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.
- X = np.array([0.5, 1.0, -1.5])

In [ ]:
X = np.array([0.5, 1.0, -1.5])
W = np.array([4, 5, 6])

x_y = np.dot(X,W)
print(x_y)

-2.0


In [ ]:
# W는 가중치 행렬, X 는 입력 벡터이고 일반적인 표기 방식은 WX
X = np.array([0.5, 1.0, -1.5])
W = np.array([[0.2, -0.3, 0.5],
             [0.4, 0.1, -0.2],
             [-0.5, 0.4, 0.3]])

output = np.dot(X,W)

print(X,'\n')
print(W,'\n')
print(output)


[ 0.5  1.  -1.5] 

[[ 0.2 -0.3  0.5]
 [ 0.4  0.1 -0.2]
 [-0.5  0.4  0.3]] 

[-0.95  0.6  -0.3 ]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산<br>
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
def relu(x):
    return np.maximum(0,x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 입력 벡터 정의

X = np.array([1, -2, 3])

W = np.array([[0.2, -0.5, 0.3],
             [0.4, 0.1, -0.2],
             [-0.3, 0.4, 0.6]])
b = np.array([0.1, -0.2, 0.3])

Z = np.dot(X,W)

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print(X,'\n')
print(W,'\n')
print(b,'\n')
print(Z,'\n')
print(output_relu,'\n')
print(output_sigmoid)


[ 1 -2  3] 

[[ 0.2 -0.5  0.3]
 [ 0.4  0.1 -0.2]
 [-0.3  0.4  0.6]] 

[ 0.1 -0.2  0.3] 

[ 2.1 -0.4  0.7] 

[2.1 0.  0.7] 

[0.89090318 0.40131234 0.66818777]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [ ]:
A = np.array([[3,4],[2,1]])
b = np.array([10,5])

#역행렬 계산
A_inv = np.linalg.inv(A)

# 해 계산
x = np.dot(A_inv , b)

print(A)
print(b)
print(A_inv)
print(x)

[[3 4]
 [2 1]]
[10  5]
[[-0.2  0.8]
 [ 0.4 -0.6]]
[2. 1.]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p`를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p`에서 원래 좌표 p를 복원.

In [ ]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 새로운 좌표 p` 계산
p_prime = np.dot(p,T)

# 변환 행렬 T의 역행렬 계산
T_inv = np.linalg.inv(T)

# 원래 좌표 P복원
p_restored = np.dot(T_inv, p_prime)

print(p_prime,'\n')
print(T_inv,'\n')
print(p_restored)


[2 6] 

[[0.5        0.        ]
 [0.         0.33333333]] 

[1. 2.]
